name: build
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    strategy:
      matrix:
        channel: [release, rc, dev]
    steps:
      - uses: actions/checkout@v3
        with:
          path: app
      - uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-ufbt
          ref: refs/heads/dev
          path: tools
      - run: echo "$GITHUB_WORKSPACE/tools" >> $GITHUB_PATH
      - uses: actions/cache@v3
        id: cache-ufbt
        with:
          path: tools/.ufbt
          key: ${{ runner.os }}-${{ matrix.channel }}-ufbt
      - run: ufbt update --channel=${{ matrix.channel }}
      - run: ufbt
      - uses: actions/upload-artifact@v3
        with:
          path: app/dist/*.fap
